# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [2]:
import torch

Construct a 5x3 matrix, uninitialized

In [27]:
x = torch.Tensor(5, 3)
print(x)

tensor([[0.0000e+00, 7.1440e+31, 7.7052e+31],
        [7.2148e+22, 1.5766e-19, 1.0256e-08],
        [1.6802e-04, 3.1300e+12, 6.9363e-07],
        [1.0504e-05, 1.6597e-07, 1.2820e+16],
        [2.1707e-18, 7.0952e+22, 1.7748e+28]])


Construct a randomly initialized matrix

In [17]:
x = torch.rand(5, 3)
print(x)

tensor([[0.9240, 0.2061, 0.7521],
        [0.8323, 0.8844, 0.4153],
        [0.5736, 0.8997, 0.7913],
        [0.1252, 0.0093, 0.7311],
        [0.1409, 0.0975, 0.9847]])


Get its size

In [4]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [18]:
x[1:3] = 2
print(x)

tensor([[0.9240, 0.2061, 0.7521],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.1252, 0.0093, 0.7311],
        [0.1409, 0.0975, 0.9847]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [8]:
x = torch.Tensor(2, 17)
print(x)

tensor([[ 5.1647e+29,  3.1582e-41, -1.8652e+15,  4.3814e-41,  8.9683e-44,
          0.0000e+00,  1.1210e-43,  0.0000e+00, -3.0638e+29,  3.1589e-41,
          4.2483e-05,  4.4202e-05,  1.0920e-05,  1.7264e-07,  2.1707e-18,
          1.6678e+19,  7.0976e+22],
        [ 2.1715e-18,  3.0135e+29,  1.7610e+19,  1.1625e+27,  1.4580e-19,
          7.1856e+22,  4.3605e+27,  1.5766e-19,  7.1856e+22,  1.5835e-43,
          0.0000e+00,  5.1158e+29,  3.1582e-41, -1.8652e+15,  4.3814e-41,
          3.3242e+21,  3.3500e-09]])


In [9]:
y = torch.FloatTensor(3,1)
print(y)

tensor([[-1.8652e+15],
        [ 4.3814e-41],
        [ 5.1611e+29]])


In [13]:
z = torch.LongTensor(5,2,1)
print(z)
z[:,:,:] = 7
print(z)

tensor([[[0],
         [0]],

        [[0],
         [0]],

        [[0],
         [0]],

        [[0],
         [0]],

        [[0],
         [0]]])
tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])


In [15]:
w = torch.ByteTensor(5,)
print(w)
w[0] = 0
w[4] = 0
w[1:4] = 1
print(w)

tensor([240,  67, 221, 113,  10], dtype=torch.uint8)
tensor([0, 1, 1, 1, 0], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [19]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.9211, 0.2366, 0.7715],
        [2.9807, 2.5165, 2.4613],
        [2.6012, 2.5430, 2.9024],
        [0.9155, 0.5489, 1.0917],
        [0.3523, 0.3578, 1.1001]])


### 2.2 Addition: syntax 2

In [20]:
print(torch.add(x, y))

tensor([[1.9211, 0.2366, 0.7715],
        [2.9807, 2.5165, 2.4613],
        [2.6012, 2.5430, 2.9024],
        [0.9155, 0.5489, 1.0917],
        [0.3523, 0.3578, 1.1001]])


### 2.3 Addition: giving an output tensor

In [21]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.9211, 0.2366, 0.7715],
        [2.9807, 2.5165, 2.4613],
        [2.6012, 2.5430, 2.9024],
        [0.9155, 0.5489, 1.0917],
        [0.3523, 0.3578, 1.1001]])


### 2.4 Addition: in-place

adds `x`to `y`

In [22]:
y.add_(x)
print(y)

tensor([[1.9211, 0.2366, 0.7715],
        [2.9807, 2.5165, 2.4613],
        [2.6012, 2.5430, 2.9024],
        [0.9155, 0.5489, 1.0917],
        [0.3523, 0.3578, 1.1001]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [23]:
print(x[:, 1])

tensor([0.2061, 2.0000, 2.0000, 0.0093, 0.0975])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [42]:
torch.Tensor.mul(x,y)

tensor([[0.0000e+00, 4.0001e+30, 4.5863e+31],
        [6.4101e+23, 9.9842e-19, 6.2129e-08],
        [1.1368e-03, 2.0242e+13, 5.8431e-06],
        [8.8031e-06, 5.0006e-08, 1.5278e+16],
        [2.6936e-19, 9.0829e+21, 2.1478e+28]])

In [33]:
x.mul_(y)

tensor([[0.0000e+00, 1.6905e+31, 5.9446e+31],
        [2.1505e+23, 3.9675e-19, 2.5243e-08],
        [4.3704e-04, 7.9597e+12, 2.0132e-06],
        [9.6160e-06, 9.1102e-08, 1.3996e+16],
        [7.6466e-19, 2.5386e+22, 1.9524e+28]])

In [44]:
torch.Tensor.div(x,y)

tensor([[0.0000e+00, 7.1440e+31, 7.7052e+31],
        [7.2148e+22, 1.5766e-19, 1.0256e-08],
        [1.6802e-04, 3.1300e+12, 6.9363e-07],
        [1.0504e-05, 1.6597e-07, 1.2820e+16],
        [2.1707e-18, 7.0952e+22, 1.7748e+28]])

In [46]:
i = torch.rand(2,4)
j = torch.rand(4,2)
torch.Tensor.mul(i,j)

RuntimeError: ignored

## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [47]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [48]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [49]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [50]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

In [52]:
c = torch.ones(5,2)
d = c.numpy()
e = torch.from_numpy(d)
print(e)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [4]:
# let us run this cell only if CUDA is available
x = torch.ones(5,3)
y = torch.rand(5,3)
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
tensor([[0.7918, 0.1381, 0.2295],
        [0.1674, 0.3201, 0.4163],
        [0.2375, 0.6168, 0.2818],
        [0.1703, 0.1808, 0.8906],
        [0.9976, 0.3173, 0.4875]], device='cuda:0')
tensor([[1.7918, 1.1381, 1.2295],
        [1.1674, 1.3201, 1.4163],
        [1.2375, 1.6168, 1.2818],
        [1.1703, 1.1808, 1.8906],
        [1.9976, 1.3173, 1.4875]], device='cuda:0')
